# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Myproj/GitHub/convAccProject/LoopBackFIFO/LoopBackFIFO.srcs/sources_1/bd/loopBackFifoBD/ip/loopBackFifoBD_processing_system7_0_0/loopBackFifoBD_processing_system7_0_0.xci
# IP: The module: 'loopBackFifoBD_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Myproj/GitHub/convAccProject/LoopBackFIFO/LoopBackFIFO.gen/sources_1/bd/loopBackFifoBD/ip/loopBackFifoBD_processing_system7_0_0/loopBackFifoBD_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'loopBackFifoBD_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Myproj/GitHub/convAccProject/LoopBackFIFO/LoopBackFIFO.srcs/sources_1/bd/loopBackFifoBD/ip/loopBackFifoBD_processing_system7_0_0/loopBackFifoBD_processing_system7_0_0.xci
# IP: The module: 'loopBackFifoBD_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Myproj/GitHub/convAccProject/LoopBackFIFO/LoopBackFIFO.gen/sources_1/bd/loopBackFifoBD/ip/loopBackFifoBD_processing_system7_0_0/loopBackFifoBD_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'loopBackFifoBD_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
