# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/loopBackFifoBD/loopBackFifoBD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loopBackFifoBD || ORIG_REF_NAME==loopBackFifoBD} -quiet] -quiet

# IP: bd/loopBackFifoBD/ip/loopBackFifoBD_axi_dma_0/loopBackFifoBD_axi_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loopBackFifoBD_axi_dma_0 || ORIG_REF_NAME==loopBackFifoBD_axi_dma_0} -quiet] -quiet

# IP: bd/loopBackFifoBD/ip/loopBackFifoBD_axi_mem_intercon_0/loopBackFifoBD_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loopBackFifoBD_axi_mem_intercon_0 || ORIG_REF_NAME==loopBackFifoBD_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/loopBackFifoBD/ip/loopBackFifoBD_axi_mem_intercon_1_0/loopBackFifoBD_axi_mem_intercon_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loopBackFifoBD_axi_mem_intercon_1_0 || ORIG_REF_NAME==loopBackFifoBD_axi_mem_intercon_1_0} -quiet] -quiet

# IP: bd/loopBackFifoBD/ip/loopBackFifoBD_processing_system7_0_0/loopBackFifoBD_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loopBackFifoBD_processing_system7_0_0 || ORIG_REF_NAME==loopBackFifoBD_processing_system7_0_0} -quiet] -quiet

# IP: bd/loopBackFifoBD/ip/loopBackFifoBD_ps7_0_axi_periph_0/loopBackFifoBD_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loopBackFifoBD_ps7_0_axi_periph_0 || ORIG_REF_NAME==loopBackFifoBD_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/loopBackFifoBD/ip/loopBackFifoBD_rst_ps7_0_100M_0/loopBackFifoBD_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loopBackFifoBD_rst_ps7_0_100M_0 || ORIG_REF_NAME==loopBackFifoBD_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/loopBackFifoBD/ip/loopBackFifoBD_axi_mem_intercon_imp_auto_pc_0/loopBackFifoBD_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loopBackFifoBD_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==loopBackFifoBD_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/loopBackFifoBD/ip/loopBackFifoBD_axi_mem_intercon_imp_auto_us_0/loopBackFifoBD_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loopBackFifoBD_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==loopBackFifoBD_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# IP: bd/loopBackFifoBD/ip/loopBackFifoBD_axi_mem_intercon_1_imp_auto_pc_0/loopBackFifoBD_axi_mem_intercon_1_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loopBackFifoBD_axi_mem_intercon_1_imp_auto_pc_0 || ORIG_REF_NAME==loopBackFifoBD_axi_mem_intercon_1_imp_auto_pc_0} -quiet] -quiet

# IP: bd/loopBackFifoBD/ip/loopBackFifoBD_ps7_0_axi_periph_imp_auto_pc_0/loopBackFifoBD_ps7_0_axi_periph_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loopBackFifoBD_ps7_0_axi_periph_imp_auto_pc_0 || ORIG_REF_NAME==loopBackFifoBD_ps7_0_axi_periph_imp_auto_pc_0} -quiet] -quiet

# IP: bd/loopBackFifoBD/ip/loopBackFifoBD_lpbk_tst_0_0/loopBackFifoBD_lpbk_tst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loopBackFifoBD_lpbk_tst_0_0 || ORIG_REF_NAME==loopBackFifoBD_lpbk_tst_0_0} -quiet] -quiet

# XDC: d:/Myproj/GitHub/convAccProject/LoopBackFIFO/LoopBackFIFO.gen/sources_1/bd/loopBackFifoBD/loopBackFifoBD_ooc.xdc
